### ISSUE TITLE
Google chrome config error

### ISSUE THREAD

**Issue by AxiomaEstudio** [andrewscwei/generator-vars-webapp#1]
With the current config for the serve task is getting me the following error:
Error: spawn google chrome ENOENT

So just changing the browser name to 'google-chrome' in the .taskconfig file it works.

**Comment by andrewscwei** [comment]
Thanks for reporting. It was actually a bad idea to assume the preferred browser in `.taskconfig`, so it is now removed in 2.0.4 (cd0d8ef). Users can define their own preferred browser if they wish or just leave it as default.
